// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Badminton.Data.Models;

public partial class Court
{
    public int CourtId { get; set; }

    public string Name { get; set; }

    public string Status { get; set; }

    public string Description { get; set; }

    public double NightPrice { get; set; }

    public double DayPrice { get; set; }

    public double WeekendDayPrice { get; set; }

    public double WeekendNightPrice { get; set; }

    public virtual ICollection<CourtDetail> CourtDetails { get; set; } = new List<CourtDetail>();
}