// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Badminton.Data.Models;

public partial class CourtDetail
{
    public int CourtDetailId { get; set; }

    public int StaffId { get; set; }

    public int CourtId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public double Price { get; set; }

    public string Status { get; set; }

    public virtual Court Court { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Customer Staff { get; set; }
}