// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Badminton.Data.Models;

public partial class CourtDetail
{
    public int CourtDetailId { get; set; }

    public int CourtId { get; set; }

    public string Slot { get; set; }

    public double Price { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public int? Capacity { get; set; }

    public int? BookingCount { get; set; }

    public virtual Court Court { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}